stages:
  - package

variables:
  GIT_STRATEGY: fetch

package-on-tag:
  stage: package
  image: ubuntu2404:20260319
  only:
    - tags
  script:
    - apt-get update
    - apt-get install -y curl ca-certificates gnupg
    - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
    - apt-get install -y nodejs
    - node -v
    - npm -v
    - chmod +x ./scripts/02-package.sh
    - ./scripts/02-package.sh
  artifacts:
    name: "tb_tool_bt_backend-${CI_COMMIT_TAG}"
    paths:
      - tar/*.tar.gz
    expire_in: 30 days
