import { ROUTE_PATHS } from './routes';
import { PAGE_PERMISSION_CODES } from './permissionCodes';
import { ROLES } from './roles';

export const sideMenuConfig = [
  {
    path: ROUTE_PATHS.DEPARTMENT_OVERVIEW,
    label: '有效工时',
    employeeLabel: '有效工时',
    section: '部门',
    allowedRoles: [ROLES.MANAGER, ROLES.ADMIN],
    permissionCode: PAGE_PERMISSION_CODES.DEPARTMENT_OVERVIEW,
  },
  {
    path: ROUTE_PATHS.WORKDAY_COSTHOUR,
    label: '工作日耗时',
    employeeLabel: '工作日耗时',
    section: '部门',
    allowedRoles: [ROLES.MANAGER, ROLES.ADMIN],
    permissionCode: PAGE_PERMISSION_CODES.WORKDAY_COSTHOUR,
  },
  {
    path: ROUTE_PATHS.ATTENDANCE,
    label: '出勤表',
    employeeLabel: '出勤表',
    section: '部门',
    allowedRoles: [ROLES.MANAGER, ROLES.ADMIN],
    permissionCode: PAGE_PERMISSION_CODES.WORKDAY_COSTHOUR,
  },
  {
    path: ROUTE_PATHS.QUARTERLY_PERFORMANCE,
    label: '季度绩效',
    employeeLabel: '季度绩效',
    section: '部门',
    allowedRoles: [ROLES.MANAGER, ROLES.ADMIN],
    permissionCode: PAGE_PERMISSION_CODES.WORKDAY_COSTHOUR,
  },
  {
    path: ROUTE_PATHS.NAV_TEAM_DETAIL,
    label: '导航组',
    employeeLabel: '导航组',
    section: '团队',
    allowedRoles: [ROLES.MANAGER, ROLES.ADMIN],
    permissionCode: PAGE_PERMISSION_CODES.NAV_TEAM_DETAIL,
  },
  {
    path: ROUTE_PATHS.INTEGRATION_TEAM_DETAIL,
    label: '对接组',
    employeeLabel: '对接组',
    section: '团队',
    allowedRoles: [ROLES.MANAGER, ROLES.ADMIN],
    permissionCode: PAGE_PERMISSION_CODES.INTEGRATION_TEAM_DETAIL,
  },
  {
    path: ROUTE_PATHS.APPLICATION_TEAM,
    label: '应用组',
    employeeLabel: '应用组',
    section: '团队',
    allowedRoles: [ROLES.MANAGER, ROLES.ADMIN],
    permissionCode: PAGE_PERMISSION_CODES.APPLICATION_TEAM,
  },
  {
    path: ROUTE_PATHS.APP_THREE_TEAM,
    label: '应用三组',
    employeeLabel: '应用三组',
    section: '团队',
    allowedRoles: [ROLES.MANAGER, ROLES.ADMIN],
    permissionCode: PAGE_PERMISSION_CODES.APP_THREE_TEAM,
  },
  {
    path: ROUTE_PATHS.PERSONAL_HOURS,
    label: '工时管理',
    employeeLabel: '工时管理',
    section: '个人',
    employeeSection: '个人',
    allowedRoles: [ROLES.EMPLOYEE, ROLES.MANAGER, ROLES.ADMIN],
    permissionCode: PAGE_PERMISSION_CODES.PERSONAL_HOURS,
  },
  {
    path: ROUTE_PATHS.PERFORMANCE,
    label: '绩效管理',
    employeeLabel: '绩效管理',
    section: '个人',
    employeeSection: '个人',
    allowedRoles: [ROLES.EMPLOYEE, ROLES.MANAGER, ROLES.ADMIN],
    permissionCode: PAGE_PERMISSION_CODES.PERFORMANCE,
  },
  {
    path: ROUTE_PATHS.AI_ANALYSIS,
    label: 'AI助理',
    employeeLabel: 'AI助理',
    section: '个人',
    employeeSection: '个人',
    allowedRoles: [ROLES.EMPLOYEE, ROLES.MANAGER, ROLES.ADMIN],
    permissionCode: PAGE_PERMISSION_CODES.AI_ANALYSIS,
  },
];
