#!/usr/bin/env python3
"""Audit the single-level BGE-M3 chunker on the six local research samples."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from transformers import AutoTokenizer

from ai.knowledge.cleaner import clean_markdown
from ai.knowledge.routes import _extract_outline_v2
from ai.knowledge.single_m3_chunker import MAX_TOKENS, chunk_document_single_m3


TABLE_SEPARATOR_RE = re.compile(r"^\s*\|?(?:\s*:?-{3,}:?\s*\|)+\s*$")


def summarize(values: list[int]) -> dict:
    if not values:
        return {"min": 0, "mean": 0, "p95": 0, "max": 0}
    ordered = sorted(values)
    p95 = ordered[min(len(ordered) - 1, int((len(ordered) - 1) * 0.95 + 0.5))]
    return {
        "min": min(values),
        "mean": round(sum(values) / len(values), 2),
        "p95": p95,
        "max": max(values),
    }


def audit_sample(root: Path, tokenizer, sample: dict) -> dict:
    raw = (root / sample["raw_file"]).read_text(encoding="utf-8")
    cleaned = clean_markdown(raw, sample["title"])
    outline = _extract_outline_v2(cleaned.cleaned_md)
    result = chunk_document_single_m3(
        sample["node_id"],
        sample["title"],
        cleaned.cleaned_md,
        json.dumps(outline, ensure_ascii=False),
        "FILE",
        sample["folder_path"],
        tokenizer=tokenizer,
    )
    chunks = result["leaf"]
    contents = [chunk["content"] for chunk in chunks]
    tokens = [chunk["token_count"] for chunk in chunks]
    table_chunks = [
        content for content in contents
        if any(line.strip().startswith("|") for line in content.splitlines())
    ]
    return {
        "slug": sample["slug"],
        "title": sample["title"],
        "chunk_count": len(chunks),
        "token_stats": summarize(tokens),
        "over_max_tokens": sum(value > MAX_TOKENS for value in tokens),
        "folder_header_coverage": sum("知识库路径：" in content for content in contents),
        "title_header_coverage": sum("文档：" in content for content in contents),
        "section_header_coverage": sum("本文目录：" in content for content in contents),
        "unbalanced_fence_chunks": sum(
            sum(line.lstrip().startswith("```") for line in content.splitlines()) % 2
            for content in contents
        ),
        "table_chunk_count": len(table_chunks),
        "table_chunks_without_separator": sum(
            not any(TABLE_SEPARATOR_RE.match(line) for line in content.splitlines())
            for content in table_chunks
        ),
        "outline_count": len(outline),
        "cleaner_warnings": cleaned.warnings,
    }


def render(rows: list[dict]) -> str:
    lines = [
        "# Single-level BGE-M3 chunk audit",
        "",
        "| Sample | Chunks | Token max | >1200 | Folder headers | Section headers | Fence errors | Table errors |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(
            f"| {row['slug']} | {row['chunk_count']} | {row['token_stats']['max']} | "
            f"{row['over_max_tokens']} | {row['folder_header_coverage']}/{row['chunk_count']} | "
            f"{row['section_header_coverage']}/{row['chunk_count']} | "
            f"{row['unbalanced_fence_chunks']} | {row['table_chunks_without_separator']} |"
        )
    lines.extend(["", "Generated by `audit_single_m3.py`.", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent)
    parser.add_argument("--model", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    root = args.root.resolve()
    model_path = args.model or root.parents[2] / "local_models" / "BAAI" / "bge-m3"
    tokenizer = AutoTokenizer.from_pretrained(model_path, local_files_only=True)
    tokenizer.model_max_length = 1_000_000
    manifest = json.loads((root / "sample_manifest.json").read_text(encoding="utf-8"))
    rows = [audit_sample(root, tokenizer, sample) for sample in manifest]
    output = args.output or root / "results" / "single_m3_candidate.json"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps({"samples": rows}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    output.with_suffix(".md").write_text(render(rows), encoding="utf-8")
    print(render(rows))


if __name__ == "__main__":
    main()
