"""API 路由索引：用于可视化查看「URL -> 处理函数 -> service」映射。"""

from typing import Dict, List


API_BT_ROUTE_INDEX: List[Dict[str, str]] = [
    # health_proxy
    {
        "module": "health_proxy",
        "method": "GET",
        "path": "/api/bt/health",
        "desc": "健康检查（用于探活/确认服务存活）",
        "handler": "base.health.routes.health",
        "service": "base.health.proxy.health_service",
    },
    {
        "module": "health_proxy",
        "method": "POST",
        "path": "/api/bt/proxy",
        "desc": "通用钉钉 API 代理转发（调试/透传用）",
        "handler": "base.health.routes.proxy_dingtalk",
        "service": "base.health.proxy.dingtalk_proxy_service",
    },
    {
        "module": "health_proxy",
        "method": "GET,POST",
        "path": "/api/bt/gettoken",
        "desc": "获取/刷新钉钉 access_token（本服务封装版）",
        "handler": "base.health.routes.gettoken",
        "service": "base.health.proxy.dingtalk_gettoken_service",
    },
    # auth
    {
        "module": "auth",
        "method": "GET",
        "path": "/api/bt/auth/dingtalk/url",
        "desc": "获取钉钉网页 OAuth 授权跳转地址（登录页用）",
        "handler": "base.auth.routes.auth_dingtalk_url",
        "service": "dingtalk_client.build_dingtalk_oauth_url",
    },
    {
        "module": "auth",
        "method": "GET",
        "path": "/api/bt/auth/local/users",
        "desc": "离线模式：获取本地 user_character 用户列表（用于登录下拉框）",
        "handler": "base.auth.routes.auth_local_users",
        "service": "base.auth.service (inline DB query)",
    },
    {
        "module": "auth",
        "method": "POST",
        "path": "/api/bt/auth/local/login",
        "desc": "离线模式本地登录：user_id + password，建立 session 不走钉钉 OAuth",
        "handler": "base.auth.routes.auth_local_login",
        "service": "base.auth.service.authenticate_local_user",
    },
    {
        "module": "auth",
        "method": "GET",
        "path": "/api/bt/auth/callback",
        "desc": "钉钉网页 OAuth 回调：用 authCode 建立 session 并重定向",
        "handler": "base.auth.routes.auth_dingtalk_callback",
        "service": "route_registry.auth._session_from_dingtalk_auth_code",
    },
    {
        "module": "auth",
        "method": "POST",
        "path": "/api/bt/auth/get_token",
        "desc": "钉钉免登：前端传 code，后端换 token + 建立 session",
        "handler": "base.auth.routes.auth_get_token",
        "service": "route_registry.auth._session_from_dingtalk_auth_code",
    },
    {
        "module": "auth",
        "method": "GET",
        "path": "/api/bt/auth/me",
        "desc": "获取当前会话用户信息（前端初始化用）",
        "handler": "base.auth.routes.auth_me",
        "service": "session.auth_user",
    },
    {
        "module": "auth",
        "method": "POST",
        "path": "/api/bt/auth/logout",
        "desc": "退出登录：清理 session",
        "handler": "base.auth.routes.auth_logout",
        "service": "session.pop(auth_user)",
    },
    # projects
    {
        "module": "updates",
        "method": "POST",
        "path": "/api/bt/time_range_update",
        "desc": "更新时间窗：按 startDate/endDate 同步 A+B（按钮用）",
        "handler": "route_registry.updates.time_range_update",
        "service": "base.sync.task_sync.sync_project_details_in_time_range_service",
    },
    {
        "module": "projects",
        "method": "POST",
        "path": "/api/bt/query_project_tasks",
        "desc": "项目任务列表查询；可选触发按 payload 时间窗同步 A/B 表",
        "handler": "base.projects.routes.query_project_tasks",
        "service": (
            "base.projects.task_service.query_project_tasks_service OR "
            "base.sync.task_sync.sync_project_details_in_time_range_service"
        ),
    },
    {
        "module": "projects",
        "method": "POST",
        "path": "/api/bt/query_task_details",
        "desc": "按用户查询任务明细（钉钉 users/{userId}/tasks）",
        "handler": "base.projects.routes.query_task_details",
        "service": "base.projects.task_service.query_user_tasks_service",
    },
    {
        "module": "projects",
        "method": "POST",
        "path": "/api/bt/query_task_detail_custom_fields",
        "desc": "读取 project_task_details 中指定 taskId 的 custom_fields_json 并拆解需求描述/任务产出",
        "handler": "base.projects.routes.query_task_detail_custom_fields",
        "service": "base.sync.task_detail_extract.extract_task_detail_custom_fields_service",
    },
    # AI tbcreate
    {
        "module": "ai.tbcreate",
        "method": "POST",
        "path": "/api/bt/ai/tbcreate/workspace/init",
        "desc": "AI 任务创建：初始化用户工作区（写入 CLAUDE.md / AI_TASK_CONTEXT.md / TASK_TICKET_RULES.md）",
        "handler": "ai.tbcreate.routes.ai_tbcreate_workspace_init",
        "service": "ai.tbcreate.workspace.init_workspace",
    },
    {
        "module": "ai.tbcreate",
        "method": "GET",
        "path": "/api/bt/ai/tbcreate/draft/current",
        "desc": "AI 任务创建：读取工作区 draft.json（手动同步按钮调用）",
        "handler": "ai.tbcreate.routes.ai_tbcreate_draft_current",
        "service": "ai.tbcreate.routes (reads workspace/draft.json from filesystem)",
    },
    {
        "module": "ai.tbcreate",
        "method": "POST",
        "path": "/api/bt/ai/tbcreate/draft/save",
        "desc": "AI 任务创建：前端编辑草稿后保存回 draft.json（供 Claude 读取）",
        "handler": "ai.tbcreate.routes.ai_tbcreate_draft_save",
        "service": "ai.tbcreate.routes (writes draft dict to workspace/draft.json)",
    },
    # config
    {
        "module": "config",
        "method": "GET",
        "path": "/api/bt/config/userids",
        "desc": "读取 ids/config 中的用户列表（用于下拉/批量更新）",
        "handler": "base.config.routes.get_config_userids",
        "service": "base.config.service.get_userids_service",
    },
    {
        "module": "config",
        "method": "GET",
        "path": "/api/bt/config/projectids",
        "desc": "读取 ids/config 中的项目列表（用于同步目标）",
        "handler": "base.config.routes.get_config_projectids",
        "service": "base.config.service.get_projectids_service",
    },
    {
        "module": "config",
        "method": "GET",
        "path": "/api/bt/config/workhour_role_coefficients",
        "desc": "读取不同角色工时系数（管理员/员工等）",
        "handler": "base.config.routes.get_config_workhour_role_coefficients",
        "service": "base.config.service.get_workhour_role_coefficients_service",
    },
    {
        "module": "config",
        "method": "GET",
        "path": "/api/bt/config/user_character",
        "desc": "读取用户角色/分组（user_character 表）",
        "handler": "base.config.routes.get_config_user_character",
        "service": "base.config.service.get_user_character_service",
    },
    {
        "module": "config",
        "method": "GET",
        "path": "/api/bt/config/last_update_time",
        "desc": "读取 last_update_time（页面显示“最后更新时间”）",
        "handler": "base.config.routes.get_config_last_update_time",
        "service": "base.config.service.get_last_update_time_service",
    },
    {
        "module": "config",
        "method": "GET",
        "path": "/api/bt/config/default_time_range",
        "desc": "读取默认 start/end/last_update_time（只读，用于页面初始化）",
        "handler": "base.config.routes.get_config_default_time_range",
        "service": "base.config.service.get_default_time_range_service",
    },
    {
        "module": "organization",
        "method": "GET",
        "path": "/api/bt/organization/scopes/{scope_code}/options",
        "desc": "按业务 Scope 返回团队和人员选项",
        "handler": "base.organization.routes.organization_scope_options",
        "service": "base.organization.service.list_scope_teams/list_scope_members",
    },
    {
        "module": "organization",
        "method": "GET",
        "path": "/api/bt/organization/scopes/{scope_code}/members",
        "desc": "按业务 Scope 返回统一人员列表",
        "handler": "base.organization.routes.organization_scope_members",
        "service": "base.organization.service.list_scope_members",
    },
    {
        "module": "config",
        "method": "POST",
        "path": "/api/bt/config/touch_last_update_time",
        "desc": "触摸 last_update_time（用于显示“最后更新时间”）",
        "handler": "base.config.routes.touch_config_last_update_time",
        "service": "base.config.service.touch_last_update_time_service",
    },
    {
        "module": "config",
        "method": "POST",
        "path": "/api/bt/config/update_endtime",
        "desc": "将 end_time 的日期更新为今天（保留原时分秒）",
        "handler": "base.config.routes.update_config_endtime",
        "service": "base.config.service.update_endtime_service",
    },
    {
        "module": "config",
        "method": "GET",
        "path": "/api/bt/config/workhour_auto_calc",
        "desc": "读取自动计算配置（是否定时触发更新）",
        "handler": "base.config.routes.get_workhour_auto_calc",
        "service": "base.config.service.get_workhour_auto_calc_service",
    },
    {
        "module": "config",
        "method": "POST",
        "path": "/api/bt/config/workhour_auto_calc",
        "desc": "更新自动计算配置（开关 + 时间点）",
        "handler": "base.config.routes.update_workhour_auto_calc",
        "service": "base.config.service.update_workhour_auto_calc_service",
    },
    {
        "module": "application_team",
        "method": "GET",
        "path": "/api/bt/application-team/options",
        "desc": "应用组（导航组应用工程师）报表筛选项",
        "handler": "application_team.routes.application_team_options",
        "service": "application_team.report_service.application_team_options_service",
    },
    {
        "module": "application_team",
        "method": "POST",
        "path": "/api/bt/application-team/report",
        "desc": "应用组问题分析报表",
        "handler": "application_team.routes.application_team_report",
        "service": "application_team.report_service.application_team_report_service",
    },
    {
        "module": "application_team",
        "method": "GET",
        "path": "/api/bt/app-three-team/options",
        "desc": "应用三组报表筛选项",
        "handler": "application_team.routes.app_three_team_options",
        "service": "application_team.report_service.application_team_options_service(APP_THREE_TEAM_VIEW)",
    },
    {
        "module": "application_team",
        "method": "POST",
        "path": "/api/bt/app-three-team/report",
        "desc": "应用三组问题分析报表",
        "handler": "application_team.routes.app_three_team_report",
        "service": "application_team.report_service.application_team_report_service(APP_THREE_TEAM_VIEW)",
    },
    # db_sync
    {
        "module": "db_sync",
        "method": "POST",
        "path": "/api/bt/db/sync/project-tasks",
        "desc": "同步项目任务到 A 表（project_tasks）",
        "handler": "route_registry.db_sync.db_sync_project_tasks",
        "service": "base.sync.task_sync.sync_project_tasks_to_db",
    },
    {
        "module": "db_sync",
        "method": "POST",
        "path": "/api/bt/db/sync/task-detail",
        "desc": "同步单个任务明细到 B/C 表（按 taskId）",
        "handler": "route_registry.db_sync.db_sync_task_detail",
        "service": "base.sync.task_sync.sync_task_detail_to_db",
    },
    {
        "module": "db_sync",
        "method": "POST",
        "path": "/api/bt/db/sync/task-details-batch",
        "desc": "批量同步任务明细到 B/C 表（批处理）",
        "handler": "route_registry.db_sync.db_sync_task_details_batch",
        "service": "base.sync.task_sync.sync_task_details_batch_to_db",
    },
    # perf
    {
        "module": "perf",
        "method": "POST",
        "path": "/api/bt/perf/fill-quarter-member",
        "desc": "绩效：填充季度成员输入（表单预填/规则落地）",
        "handler": "performance.routes.perf_fill_quarter_member",
        "service": "performance.service.fill_member_input_service",
    },
    {
        "module": "perf",
        "method": "POST",
        "path": "/api/bt/perf/calculate-quarter-member",
        "desc": "绩效：计算季度成员结果（汇总/评分）",
        "handler": "performance.routes.perf_calculate_quarter_member",
        "service": "performance.service.calculate_member_quarter_performance_service",
    },
    # stats
    {
        "module": "stats",
        "method": "POST",
        "path": "/api/bt/stats/workdays",
        "desc": "统计：计算区间内法定工作日/节假日等（若启用）",
        "handler": "base.stats.routes.stats_workdays",
        "service": "workhour.personal.aggregate.workdays_in_range_service",
    },
    {
        "module": "stats",
        "method": "POST",
        "path": "/api/bt/stats/executor_quarter_workhours",
        "desc": "统计：从 DB 聚合某执行人季度工时与任务明细（dashboard 用）",
        "handler": "base.stats.routes.stats_executor_quarter_workhours",
        "service": "workhour.personal.aggregate.executor_quarter_workhours_db_service",
    },
    {
        "module": "stats",
        "method": "POST",
        "path": "/api/bt/stats/software_dev_count_last_year",
        "desc": "统计：按配置最近一年窗口统计软件开发任务数量",
        "handler": "base.stats.routes.stats_software_dev_count_last_year",
        "service": "base.projects.task_service.count_software_dev_tasks_in_config_last_year_service",
    },
]


API_DASHBOARD_ROUTE_INDEX: List[Dict[str, str]] = [
    {
        "module": "dashboard",
        "method": "GET",
        "path": "/api/dashboard/personal-hours",
        "desc": "员工工时页：默认结构（含默认时间范围、成员选项）",
        "handler": "route_registry.dashboard.personal_hours.personal_hours",
        "service": "route_registry.dashboard.personal_hours._build_default_personal_hours_payload",
    },
    {
        "module": "dashboard",
        "method": "POST",
        "path": "/api/dashboard/personal-hours/query",
        "desc": "员工工时页：查询（当前主要返回结构+回显时间）",
        "handler": "route_registry.dashboard.personal_hours.personal_hours_query",
        "service": "route_registry.dashboard.personal_hours._build_default_personal_hours_payload",
    },
    {
        "module": "dashboard",
        "method": "POST",
        "path": "/api/dashboard/personal-hours/update",
        "desc": "员工工时页：更新/全量更新入口（当前前端已直连 /api/bt/*）",
        "handler": "route_registry.dashboard.personal_hours.personal_hours_update",
        "service": "base.sync.task_sync.sync_project_details_in_time_range_service",
    },
]


def get_all_route_index() -> Dict[str, List[Dict[str, str]]]:
    return {
        "api_bt": API_BT_ROUTE_INDEX,
        "api_dashboard": API_DASHBOARD_ROUTE_INDEX,
    }
